name: Build

on:
  push:
    branches:
      - "**"
      - "!master"
    tags-ignore:
      - "**"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 (Eclipse Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Print cwd
        run: echo $PWD
      - name: Build fat JAR
        uses: gradle/gradle-build-action@v2.1.3
        with:
          arguments: shadowJar
