name: Build

on:
  push:
    branches:
      - "**"
      - "!master"
    tags-ignore:
      - "**"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17 (Eclipse Temurin)
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build fat JAR
        run: ./gradlew shadowJar --no-daemon
