name: Full cycle (build and deploy to AWS)
on:
  push:
    tags:
      - "v*"
env:
  BUILD_ARTIFACT_NAME: app
  JAR_NAME: mylittlebudget-bot-tg-fat.jar
  DEPLOY_DIR_PATH: deploy
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build fat JAR
        shell: bash
        run: ./gradlew shadowJar
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: build/libs/${{ env.JAR_NAME }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DEPLOY_DIR_PATH }}
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.BUILD_ARTIFACT_NAME }}
          path: ${{ env.DEPLOY_DIR_PATH }}
      - name: Create Procfile
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: |
          echo "web: java -jar $JAR_NAME $BOT_TOKEN $CHAT_ID $SPREADSHEET_ID" > Procfile
      - name: Set TAG_NAME var
        run: |
          echo ::set-env name=TAG_NAME::$(echo "${GITHUB_REF##*/}")
      - name: Set SOURCE_BUNDLE_NAME var
        run: |
          echo ::set-env name=SOURCE_BUNDLE_NAME::$(echo "mylittlebudget-bot-tg-$TAG_NAME.zip")
      - name: Zip source bundle
        run: |
          zip $SOURCE_BUNDLE_NAME $JAR_NAME Procfile
      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@v10
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mlb-tg-bot-fa
          environment_name: MlbTgBotFa-env
          version_label: ${{ env.TAG_NAME }}
          region: us-east-2
          deployment_package: ${{ env.DEPLOY_DIR_PATH }}/${{ env.SOURCE_BUNDLE_NAME }}
